Repository chickengak/nzmrhj, pull requests merged in 2024-02, with the labels that each got.

#4 Adapt left,right,no sidebar
  mysite/mysite/settings.py
  mysite/polls/templates/index.html
  mysite/polls/templates/left-sidebar.html
  mysite/polls/templates/no-sidebar.html
  mysite/polls/templates/right-sidebar.html
  mysite/polls/urls.py
  mysite/polls/views.py
Labels: enhancement

#7 Adapt and make chaneable templates
  mysite/polls/templates/index.html
  mysite/polls/templates/left-sidebar.html
  mysite/polls/templates/my_exam.html
  mysite/polls/templates/my_for.html
  mysite/polls/templates/my_template.html
  mysite/polls/templates/no-sidebar.html
  mysite/polls/templates/right-sidebar.html
  mysite/polls/urls.py
  mysite/polls/views.py
Labels: enhancement

#10 ALTER container and Fix a bug
  .devcontainer/devcontainer.json
  .gitignore
  mysite/polls/urls.py
Labels: bug

#12 Fix some bugs
  mysite/mysite/settings.py
  mysite/polls/templates/index.html
  mysite/static/images/banner.jpg
  mysite/static/images/pic01.jpg
  mysite/static/images/pic02.jpg
  mysite/static/images/pic03.jpg
  mysite/static/images/pic04.jpg
  mysite/static/images/pic05.jpg
Labels: bug

#14 Delete unnecessary content in index.html
  mysite/polls/templates/index.html
Labels: enhancement

#18 Save to DB
  mysite/polls/admin.py
  mysite/polls/migrations/0001_initial.py
  mysite/polls/migrations/0002_rename_inputdata_inputdatamodel.py
  mysite/polls/models.py
  mysite/polls/templates/index.html
  mysite/polls/urls.py
  mysite/polls/views.py
Labels: enhancement

#22 Reduce useless tab
  mysite/polls/templates/index.html
  mysite/polls/templates/no-sidebar.html
Labels: enhancement

#30 no_sidebar_change
  mysite/polls/templates/no-sidebar.html
  mysite/static/images/seoul.png
  mysite/static/images/seoul2.png
  mysite/static/images/seoulimg.png
Labels: enhancement

#32 Complete ML model's input and output
  mysite/mysite/urls.py
  mysite/polls/templates/index.html
  mysite/polls/views.py
Labels: bug, enhancement

#34 index, no-sidebar, kbland data
  mysite/polls/templates/index.html
  mysite/polls/templates/no-sidebar.html
  mysite/polls/views.py
  mysite/static/images/apt.png
  mysite/static/images/seoul.png
  mysite/static/images/seoul2.png
  mysite/static/images/seoulimg.png
Labels: enhancement

#36 apt.png
  mysite/polls/templates/index.html
  mysite/polls/templates/no-sidebar.html
  mysite/static/images/seoul3.png
Labels: enhancement

#38 index_html, no_sidebar
  mysite/polls/templates/index.html
  mysite/polls/templates/no-sidebar.html
  mysite/static/images/pic01.jpg
  mysite/static/images/pic02.jpg
  mysite/static/images/pic03.jpg
  mysite/static/images/pic04.jpg
  mysite/static/images/pic05.jpg
  mysite/static/images/price.png
  mysite/static/images/seoul2.png
  mysite/static/images/seoulgu.png
Labels: enhancement

#40 change title and add comment
  mysite/polls/templates/index.html
  mysite/polls/templates/no-sidebar.html
Labels: enhancement

#42 fix_headerandallowedhosts
  mysite/mysite/settings.py
  mysite/polls/templates/no-sidebar.html
Labels: enhancement

#45 summary
  mysite/polls/templates/no-sidebar.html
Labels: enhancement
